## Basic Configuration
baseURL = "https://morgancreekmore.me/"
languageCode = "en-us"
title = "Morgan Creekmore"

theme = "hyde-hyde"

## Hugo Built-in Features
googleAnalytics = "UA-66010416-1"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Morgan Creekmore"
    description = "Doing Stuff"
    #authorimage = "/img/author.jpg"
    dateformat = "Jan 2, 2006"
    themeColor = "theme-base-darkblue"
    highlightjs = true
    highlightjslanguages = ["go", "armasm"]
    highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "gamingrobot"
    linkedin = "https://www.linkedin.com/pub/morgan-creekmore/2b/65a/71a"
    twitter = "gamingrobot"
    stackoverflow = "1161491"
    email = "morgan@creekmore.email"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 300
    identifier = "projects"
    url = "/projects/"
[[menu.main]]
    name = "Contributions"
    weight = 400
    identifier = "contributions"
    url = "/contributions/"
[[menu.main]]
    name = "Search"
    identifier = "search"
    weight = 500
    url = "/search/"