## Basic Configuration
baseURL = "https://morgancreekmore.me/"
languageCode = "en-us"
title = "Morgan Creekmore"

theme = "vncnt-hugo"

## Hugo Built-in Features
googleAnalytics = "UA-66010416-1"
disableRSS = true
# enableRobotsTXT = true

[params]
  author = "Morgan Creekmore"
  email = "morgan@creekmore.email"
  keywords = "developer"
  info = "Doing Stuff"
  description = "Doing Stuff"
  bio = """
  I work as a Software Engineer doing C#/.NET Development. 
  
  In my free time I like to tinker with my personal infrastructure, code up little projects, and play video games.

  You can check out my blog at [doingstuff.dev](https://www.doingstuff.dev)
```
A1E3 8483 A2BD 883B 3C2F AF5C 004C 4990 77AE E603
https://keybase.io/gamingrobot/key.asc
```
"""
  avatar = "images/profile.png"
  favicon = "favicon.png"

  [params.contact]
    keybase = "https://keybase.io/gamingrobot"
    stack-overflow = "https://stackoverflow.com/users/1161491"
    linkedin = "https://www.linkedin.com/in/morgancreekmore"
    twitter = "https://twitter.com/gamingrobot"
    github = "https://github.com/gamingrobot"