## Basic Configuration
baseURL = "https://morgancreekmore.me/"
languageCode = "en-us"
title = "Morgan Creekmore"

theme = "hyde-hyde"

## Hugo Built-in Features
googleAnalytics = "UA-66010416-1"
# enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

## Site Settings
[params]
    author = "Morgan Creekmore"
    description = "Doing Stuff"
    #authorimage = "/img/author.jpg"
    dateformat = "Jan 2, 2006"
    themeColor = "theme-base-darkblue"
    highlightjs = true
    #highlightjslanguages = ["go", "armasm"]
    highlightjsstyle = "github"

    relatedPosts = false
    postNavigation = true

## Social Accounts
[params.social]
    github = "gamingrobot"
    linkedin = "morgancreekmore"
    twitter = "gamingrobot"
    stackoverflow = "1161491"
    email = "morgan@creekmore.email"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 300
    identifier = "projects"
    url = "/projects/"
[[menu.main]]
    name = "Search"
    identifier = "search"
    weight = 400
    url = "/search/"